### ISSUE TITLE
ImportError: No module named redis

### ISSUE THREAD

**Issue by Mazuco** [juliarizza/helpdeskbot#1]
Olá, eu testei o seu código, mas antes é necessário instalar o redis

Quando fui importar pela shell,deu erro

`>>> from main import updater
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "main.py", line 6, in <module>
    import redis
ImportError: No module named redis
`

A solução foi: sudo pip install redis 

Abraços.

**Comment by juliarizza** [comment]
Resolvido.
