### ISSUE TITLE
AttributeError: ConfigParser instance has no attribute 'read_file'

### ISSUE THREAD

**Issue by Mazuco** [juliarizza/helpdeskbot#2]
Olá, quando vou usar o comando `from main import updater` ele dá esse erro logo abaixo, mas não sei como resolver. 

from main import updater
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "main.py", line 17, in <module>
    config.read_file(open('config.ini'))
AttributeError: ConfigParser instance has no attribute 'read_file'

**Comment by juliarizza** [comment]
Executar o programa utilizando Python 3.x
